# Server configurations
server:
  port: 8081

# Spring configurations
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dcashdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: never #never, always
  jpa:
    datebase: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update #update, create-drop
    properties :
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# App global configurations
app:
  security:
    jwt:
      header: Authorization
      prefix: Bearer
      expiration: 86400 #accessToken expires in 24 hours
      refresh:
        expiration: 8640000000 # refreshToken never expire 100 000 days
      secret: 0A7A690F19001C887DEB108AE40C54717E740385243437A863569C91BF8AC99B
  init:
    admin-username: admin
    admin-password: admin
  token:
    login-code-duration: 86400
