# Server configurations
server:
  port: 8080
  servlet:
    context-path: /api/v1

# Spring configurations
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dcashdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always #never, always
  jpa:
    datebase: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create #update, create-drop
    properties :
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
